image: peaceiris/hugo

variables:
    BASEURL: "https://palashbauri.in/"

before_script:
    - apk update
    - apk add --update npm


pages:
    stage: deploy
    script:
    - apk add git
    - git submodule update --init
    - npm install
    - hugo --baseURL ${BASEURL}
    artifacts:
        paths:
        - public
    only:
        - main