image: peaceiris/hugo:v0.88.0-full

variables:
    BASEURL: "https://palashbauri.in/"


pages:
    stage: deploy
    script:
    - git submodule update --init
    - npm install
    - hugo --baseURL ${BASEURL}
    artifacts:
        paths:
        - public
    only:
        - main