image: alpine:latest

variables:
    BASEURL: "https://palashbauri.in/"
    HUGO_VERSION: "0.88.1"
    HUGO_CHECKSUM: "51850899dcd76f71c76004b9be28c7c1ea1b645d7227ff79534f773acd5e88fe"

before_script:
    - apk update
    - apk add curl
    - apk add --update npm
    - apk add --update hugo=0.88.1-r1

pages:
    stage: deploy
    script:
    - apk add git
    - git submodule update --init
    - npm install
    - hugo --baseURL ${BASEURL}
    artifacts:
        paths:
        - public
    only:
        - main